### PR TITLE
Add thelio-mira-r4

### PR DESCRIPTION
**Pull request by leviport**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by garrettjwilke — CHANGES_REQUESTED** [review]
mira-r4 is not listed in the firmware section in settings.
screenshot attached:
firmware-mira-r4

**Comment by leviport** [comment]
I got it to show up (I think it just needed updates), and now it prompts constantly about updates, even though there is no updated available.
IMG_20241213_142028_903

The version 3.11SP01 is what shows up in dmidecode, but it does not pass validation if I update the firmware changelog to match that:
```
     Running `firmware-edit/target/release/system76-firmware-edit validate thelio-mira-r4`
thelio-mira-r4 none
firmware-edit: failed to validate: Changelog entry 0 bios is '3.11.SP01', not '5.35'
```

**Comment by leviport** [comment]
Ok, I think I fixed it in the validator. Ready for re-testing.

**Review by garrettjwilke — APPROVED** [review]
firmware-mira-r4-working

**Pull request merged**
