### PR TITLE
Support for transitioning to open firmware

### PR DESCRIPTION
**Pull request by jackpot51**
This will allow for firmware built from https://github.com/system76/firmware-open/pull/118 to be downloaded, once it is published, using the --open command line parameter for system76-firmware-cli

### CODE REVIEW

**Comment by jackpot51** [comment]
It probably makes sense for system76-firmware to be a dependency of something if that's how you transition.

**Comment by leviport** [comment]
This is looking great on darp6. I have switched between open and proprietary EC multiple times.

**Comment by leviport** [comment]
The 1660Ti gaze15 is also transitioning nicely between open and proprietary firmware and EC.

**Review by crawfxrd — APPROVED** [review]

**Review by leviport — APPROVED** [review]
Darp6 and gaze15 (1660Ti) are both still looking good. We just need to make sure a 1650/1650Ti gaze15 and the addw2 are both good. I believe @jackpot51 has both and can confirm they're good before merging.

**Pull request merged**
