### PR TITLE
Handle date field in changelog

### PR DESCRIPTION
**Pull request by crawfxrd**
I'm adding a `date` field for each release.

### CODE REVIEW

**Comment by XV-02** [comment]
I'm uncertain if this is a problem with this PR or with https://github.com/system76/firmware/pull/427 but I'm not seeing the date displayed with the change-log. My gut says that the Firmware change should work, so I'm relaying this here:

When looking at the firmware panel in `gnome-control-center`, I'm not seeing the date reported. From a quick look, I think that `gnome-control-center` relies on `firmware-manager` for its change log support. That might also need a date-field PR potentially.

When passing --help to the CLI for system76-firmware, I don't see an option for version/change-log information, but apt policy does report the correct version for this PR.

Is there a specific way this need to be tested?

**Comment by crawfxrd** [comment]
The date isn't added yet in the changelogs, so you won't see it in `changelog.json`. Modify system76-firmware as described in https://github.com/system76/firmware/pull/407#issuecomment-1210887883 to use a custom `changelog.json` for testing.

This just handles the field so this/firmware-manager don't potentially die on the deserialization. It is not exposed through any UI yet.

**Comment by XV-02** [comment]
Building this PR from source - with the tweak from https://github.com/system76/firmware/pull/407#issuecomment-1210887883 to allow the use of an arbitrary `changelog.json` - and then using the `changelog.json` for thelio-mira-b1 from https://github.com/system76/firmware/pull/427 and adding another entry to the `changelog.json` to confirm the correct file is being read did not result in the date being displayed.

**Comment by XV-02** [comment]
Building this PR from source - with the tweak from https://github.com/system76/firmware/pull/407#issuecomment-1210887883 to allow the use of an arbitrary `changelog.json` - and then using the `changelog.json` for thelio-mira-b1 from https://github.com/system76/firmware/pull/427 and adding another entry to the `changelog.json` to confirm the correct file is being read did not result in the date being displayed. (So, not exposed through UI)

The package built successfully with `dpkg-buildpackage`, and the `Firmware` panel displayed the information without obvious issue. I don't see any regressions with this. 

I did note an issue in both this branch and the Master branch where `sudo make all` failed due to an inability to find the `dbus` dependency even though installed.

Is that the desired level of functionality?

**Comment by crawfxrd** [comment]
The two things to test are:

- Changelog entry with `date` set
- Changelog entry without `date`

You can them open firmware-manager to force reading it. If it works then it should be fine.

Logs could be checked with:

```
sudo journalctl -b -u system76-firmware-daemon
```

**Review by XV-02 — APPROVED** [review]
Adding the `date` data type causes no regressions and changelogs both with and without `date` parse correctly.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
