### PR TITLE
Add thelio-mira-b4 and pang12

### PR DESCRIPTION
**Pull request by leviport**

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Review by 13r0ck — CHANGES_REQUESTED** [review]
Revoking previous approval because of https://github.com/pop-os/system76-firmware/pull/106#discussion_r1063936450

**Comment by leviport** [comment]
Combined both into one.

**Review by 13r0ck — APPROVED** [review]
Thanks!

**Review by jacobktm — COMMENTED** [review]
This is good on Mira-B4

**Comment by leviport** [comment]
Also good on pang12. @jacobktm could you approve this? I forgot it was my own PR so I can't approve it myself.

**Review by jacobktm — APPROVED** [review]

**Pull request merged**
