### PR TITLE
Thelio Io firmware update support

### PR DESCRIPTION
**Pull request by jackpot51**
This is still a WIP. It will add support for firmware updates for Thelio Io boards.

### CODE REVIEW

**Comment by jackpot51** [comment]
I can demonstrate how to test using the dbus API if needed. GUI will be developed elsewhere

**Comment by jackpot51** [comment]
I added something to the `system76-firmware` package:

```
sudo system76-firmware-cli thelio-io
```

**Comment by mmstick** [comment]
Quick test on my Thelio Major returns this

```
# sudo system76-firmware-cli thelio-io
downloading manifest.json
downloading metadata.json
downloading main.hex
Switching devices to bootloader
 "/sys/bus/usb/devices/1-12"
  revision: ""
  switching to bootloader
system76-firmware: failed to update: Connection timed out (os error 110)
```

**Comment by jackpot51** [comment]
@mmstick you need to update system76-io-dkms and reboot

**Comment by mmstick** [comment]
Even after reinstalling system76-io-dkms, it's getting the same issue.

**Comment by jackpot51** [comment]
@mmstick are you still getting issues with this change?

**Comment by mmstick** [comment]
I'm still getting

```
Switching devices to bootloader
 "/sys/bus/usb/devices/1-12"
  already in bootloader
 "/sys/bus/usb/devices/1-11"
  revision: ""
  switching to bootloader
system76-firmware: failed to update: Connection timed out (os error 110)
```

```
system76-firmware:
  Installed: 1.0.5~1559677055~19.04~565598b
  Candidate: 1.0.5~1559677055~19.04~565598b
  Version table:
 *** 1.0.5~1559677055~19.04~565598b 1002
       1002 http://apt.pop-os.org/staging/thelio-io disco/main amd64 Packages
```

```
system76-io-dkms:
  Installed: 1.0.1~1559663713~19.04~ea5f61a
  Candidate: 1.0.1~1559663713~19.04~ea5f61a
  Version table:
 *** 1.0.1~1559663713~19.04~ea5f61a 1001
```

**Comment by jackpot51** [comment]
I think one of your boards is either pre-production or running pre-production firmware

**Comment by jackpot51** [comment]
@mmstick's board was running firmware before the first version, 0.0.0. That firmware did not have the bootloader command implemented, and was never used for production. I have updated him to the first production firmware. Please let me know if things are working now!

**Comment by mmstick** [comment]
All is good now

**Pull request merged**
