### PR TITLE
1.0.34: Add gaze17

### PR DESCRIPTION
**Pull request by crawfxrd**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — DISMISSED** [review]

**Comment by XV-02** [comment]
Testing this, the CLI failed when asked to schedule for next reboot.
The issue was:
```system76-firmware: failed to download: gaze17-3060-b_df60b821b2f5c45288098dba9e084aeb79d491d4133f84b73d298155aba6597e.tar.xz not found```

**Comment by crawfxrd** [comment]
Rebased, dropped unused `gaze17-3060` ID.

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
Running the CLI tool still renders the following:
`system76-firmware: failed to download: gaze17-3060-b_df60b821b2f5c45288098dba9e084aeb79d491d4133f84b73d298155aba6597e.tar.xz not found`

The tool works, and version is iterated correctly, and evidently the CLI tool is correctly identifying the model information, so I do not know if this is an acceptable state to approve, and it's merely waiting on other elements to be put in place, or if this represents an actual, blocking failure?

**Review by XV-02 — APPROVED** [review]
System76-Firmware is correctly identifying the hardware and attempting to pull firmware, and has no regressions. It's good to go.

**Pull request merged**
